@baseUrl = http://localhost:8080

### get short url
GET {{baseUrl}}/short-url?oriUrl=https://dass.com
Content-Type: text/plain

### get original url
GET {{baseUrl}}/ori-url?shortUrl=YDmVL.ai
Content-Type: text/plain