@baseUrl = http://localhost:8080

### get short url
GET {{baseUrl}}/short-url?oriUrl=https://dass.com
Content-Type: application/json

### get original url
GET {{baseUrl}}/ori-url?shortUrl=KzKeC.ai
Content-Type: application/json